contracts/base/BlacklistableUpgradeable.sol
contracts/base/FaucetCallerUpgradeable.sol
contracts/base/PausableExUpgradeable.sol
contracts/base/RandomableUpgradeable.sol
contracts/base/RescuableUpgradeable.sol
contracts/base/WhitelistableExUpgradeable.sol
contracts/base/WhitelistableUpgradeable.sol
contracts/common/OnchainRandomProvider.sol
contracts/periphery/MultisendUpgradeable.sol
contracts/periphery/PixCashierUpgradeable.sol
contracts/rewards/SpinMachineUpgradeable.sol
contracts/rewards/SpinMachineV2Upgradeable.sol
contracts/tokens/BRLCTokenUpgradeable.sol
contracts/tokens/SubstrateBRLCTokenV2Upgradeable.sol

The following has been done:
1. Tags `@notice` have been replaced with `@dev`. Motivation: a) To unify with OpenZeppelin's code. b) To ensure that the content of all tags gets into one section of the generated docs (tags `@title`, `@param`, `@return`, `@dev` are placed in one section of dosc and tags `@notice` are placed into another section).
2. The point symbol (`.`) has been added at the end of all sentences in comments, except sentences after the `@title` tag. It needs to prettify the generated docs.
3. The semicolon character (`;`) has been added to enums.  
4. Minor grammatical inaccuracies in comment text have been fixed.

Improve contract comments

---

.gitignore
contracts/base/interfaces/IERC20Wrapper.sol
contracts/tokens/BRLCWrapperUpgradeable.sol
test/tokens/BRLCWrapperUpgradeable.test.ts

Small improvements in the BRLC wrapper contract have been introduced.
The tests for the contract have been developed.
The new tests have been successfully run on the following blockchains:
1. Internal Hardhat net.
2. Ganache taken from [here](https://github.com/trufflesuite/ganache-ui/releases/tag/v2.6.0-beta.3).
3. Substrate with Frontier layer built from [this repo](https://github.com/cloudwalk/frontier-node-template).
NOTE: See notes about test running from [PR#4](https://github.com/cloudwalk/brlc-token/pull/4).
Coverage:

Implement tests for the BRLC wrapper contract

---

contracts/base/interfaces/IERC20Bridgeable.sol
contracts/bridges/MultiTokenBridgeUpgradeable.sol
contracts/bridges/TokenBridgeUpgradeable.sol
contracts/mocks/tokens/ERC20UpgradeableMock.sol
contracts/tokens/core/BridgeableTokenUpgradeable.sol
test/bridges/MultiTokenBridgeUpgradeable.test.ts
test/bridges/TokenBridgeUpgradeable.test.ts
test/tokens/core/BridgeableTokenUpgradeable.test.ts

1. Relocation nonce sequences have been separated for each chain ID.
2. The emitted events of the single-token bridge contract have been redefined with removing the `indexed` keyword for the `nonce` field.
3. The `getRelocationsData()` function has been introduced to simplify interaction with the bridge contract from a future bridge management application.
5. In the [IERC20Bridgeable](https://github.com/cloudwalk/brlc-token/blob/token-bridge-improvements/contracts/base/interfaces/IERC20Bridgeable.sol) interface function `bridge()` has been replaced with function `isBridgeSupported(address bridge)` to hide details of the internal implementation of the token's supporting for bridge operations. For the interface usage it is important only whether a bridge is supported by the token or not.
6. …

Token bridge improvements

---

contracts/InfinitePointsToken.sol
test/InfinitePointsToken.test.ts

The `InfinitePointsToken` (IPT) token contract for a new reward program has been developed.
1. The contract is inherited from the `BRLCTokenBase` contract.
2. Number of decimals is 6 by default.
3. There are no `mint()` and `birn()` functions.
4. All the tokens (total supply) are minted at the contract initialization stage and granted to the owner for further distribution.
5. The total supply of tokens is passed as an argument of the initialize function along with the token name and symbol.
The newly developed tests have been successfully run on the following blockchains:
1. Internal Hardhat net.
2. Substrate with Frontier layer built from the [cloudwalk-network](https://github.com/cloudwalk/cloudwalk-network) repo, commit [350445547016ce83c5ce781ac8871194439b0e4f](https://github.com/cloud …

Infinite points token

---

.openzeppelin/unknown-2008.json
.openzeppelin/unknown-2009.json
contracts/base/common/BlacklistableUpgradeable.sol
docs/deployed-contracts.md
test/base/common/BlacklistableUpgradeable.test.ts

The new error `ZeroAddressToBlacklist` was created to remove the possibility to blacklist the zero address, because zero address is used for burning operations and it should not be blacklisted.
Function `blacklist` now will be reverted if zero address is passed as a function parameter. Function `unblacklist` still can remove zero address from the blacklist.
New feature is covered with tests.

Removed the possibility to blacklist zero address

---

.openzeppelin/unknown-2008.json
.openzeppelin/unknown-2009.json
contracts/base/ERC20Base.sol
contracts/base/ERC20Bridgeable.sol
contracts/base/ERC20Freezable.sol
contracts/base/ERC20Mintable.sol
contracts/base/ERC20Restrictable.sol
contracts/base/interfaces/IERC20Hook.sol
contracts/base/interfaces/periphery/IBalanceTracker.sol
contracts/base/interfaces/periphery/IYieldStreamer.sol
contracts/harnesses/BalanceTrackerHarness.sol
contracts/harnesses/ERC20Harness.sol
contracts/harnesses/YieldStreamerHarness.sol
contracts/mocks/BalanceTrackerMock.sol
contracts/mocks/ERC20MockForBalanceTracker.sol
contracts/periphery/BalanceTracker.sol
contracts/periphery/YieldStreamer.sol
docs/deployed-contracts.json
docs/deployed-contracts.md
test/periphery/BalanceTracker.test.ts
test/periphery/YieldStreamer.test.ts

1. The `BalanceTracker` smart-contract has been developed. It can be attached to a ERC20 token as a hook contract to record balances at the end of the day. 
2. The `YieldStreamer` smart-contract has been developed. It is used in conjunction with the `BalanceTracker`contract  to calculate and send yield to customers based on their past token balances. The yield is stored in the account of the `YieldStreamer` contract until it is explicitly claimed by a customer. The yield is accrued to customers continuously, changing with each new request to the contract, which creates a yield stream effect. 
3. The set of harness versions of contracts have been developed for testing of the balance tracking and yield streaming logic. Those contracts provide additional functions to change their storage …

Introduce balance tracking and yield streaming

---

.openzeppelin/unknown-2008.json
.openzeppelin/unknown-2009.json
contracts/base/common/BlacklistableUpgradeable.sol
docs/deployed-contracts.md
test/BRLCToken.test.ts
test/BRLCTokenBridgeable.test.ts
test/InfinitePointsToken.test.ts
test/LightningBitcoin.test.ts
test/USJimToken.test.ts
test/base/ERC20Base.test.ts
test/base/ERC20Freezable.test.ts
test/base/ERC20Hookable.test.ts
test/base/ERC20Mintable.test.ts
test/base/common/BlacklistableUpgradeable.test.ts

<h2>1. Main changes</h2>
1. The possibility to configure multiple ```blacklister``` accounts was added.
<h2>1. Description</h2>
The description of the feature:
1. ```_blacklister``` role was changed to ```_mainBlacklister``` role.
2. ```_mainBlacklister``` can now configure multiple blacklisters with ```configureBlacklister``` role.
3. Constant variable ```_MAP_STORAGE_SLOT``` was introduced to define a memory slot that will hold the mapping of the configured blacklisters.
The new data struct was created to store the data about the configured blacklisters:
```js
struct MappingSlot {
mapping (address => bool) blacklisters;
}
```
Blacklisters are now configured with the new function that creates and stores a mapping in the storage slot:
```js
function _getMap(bytes32 slot) internal view …
```

Multiple blacklisters

---

contracts/base/interfaces/periphery/IYieldStreamer.sol
contracts/harnesses/BalanceTrackerHarness.sol
contracts/harnesses/ERC20Harness.sol
contracts/harnesses/HarnessAdministrable.sol
contracts/harnesses/YieldStreamerHarness.sol
contracts/periphery/YieldStreamer.sol
test/periphery/YieldStreamer.test.ts

1. A new role has been introduced: `harness admin`. The role is introduced through a new abstract contract named `HarnessAdministrable`.
2. Some state-changing functions of harness contracts can now be called only by an account with the `harness admin` role, not by the owner as it was previously.
3. The additional state of the `BalanceTrackerHarness` contract (variables `currentBlockTimestamp` and `usingRealBlockTimestamps`) have been moved to a pseudo-random storage slot. It allows expansion of the base `BalanceTracker` contract without affecting the state of the harness. 
4. The state of the `HarnessAdministrable` contract is also stored in a pseudo-random slot.
5. Function renaming:
* `currentBlockTimestamp()` => `getCurrentBlockTimestamp()`;
* `usingRealBlockTimestamps()` => …

Harness contracts update

---

contracts/base/interfaces/periphery/IYieldStreamer.sol
contracts/periphery/YieldStreamer.sol
test/periphery/YieldStreamer.test.ts

1. The `fee` value is rounded upward to `10000 uBRLC` (`0.01 BRLC`). E.g.: `0.225 BRLC` => `0.23 BRLC`; `0.450 BRLC` => `0.45 BRLC`.
2. The `yield` value is rounded down to `10000 uBRLC` (`0.01 BRLC`). E.g.:  `0.775 BRLC` => `0.77 BRLC`; `1.550 BRLC` => `1.55 BRLC`.
3. A new field named `yield` has been added to the `ClaimResult` structure. The new field corresponds to the final yield amount (before applying the fee) that can be requested during the `claim()` function call.
*A note:* The `ClaimResult` structure returns when a user calls the `claimPreview()` or `claimAllPreview()` functions. 
4. The rounded fields in the `ClaimResult` structure are: `yield`, `fee`. All other fields are non-rounded.
5. The `claimAll()` function has been removed from the contract to provide proper yield …

YieldStreamer update

---

contracts/base/ERC20Base.sol
contracts/base/ERC20Mintable.sol
contracts/base/common/BlacklistableUpgradeable.sol
contracts/mocks/base/common/BlacklistableUpgradeableMock.sol
test/base/ERC20Mintable.test.ts
test/base/common/BlacklistableUpgradeable.test.ts

1. A new `notBlacklistedOrBypassIfBlacklister` modifier on the `BlacklistableUpgradeable` base contract was introduced. When used, the modifier throws if the passed account is blacklisted but at the same time allows to bypass this check if the function caller is configured with the `blacklister` role.
2. The `ERC20Base` contract was updated by adopting the new modifier. 
Introduced changes have been fully covered with tests.

Blocklist base contract update

---

contracts/mocks/BalanceTrackerMock.sol
contracts/periphery/YieldStreamer.sol
test/periphery/YieldStreamer.test.ts

1. The `getDailyBalancesWithYield()` function has been introduced to the YieldStreamer smart-contract:
```solidity
/**
* @notice Returns the daily balances with yield for a specified account and period of days
* @param account The address of the account to get the balances with yield for
* @param fromDay The index of the first day of the period
* @param toDay The index of the last day of the period
*/
function getDailyBalancesWithYield(
address account,
uint16 fromDay,
uint16 toDay
) external view returns (uint256[] memory) {}
```
2. The new functions returns the daily balances for an account with the addition of possible daily yield. The returned values are the same as if the account claims all available yield (if any exists) at the end of each day within the requested period of days …

Getting balances with yield from the YieldStreamer contract

---

.openzeppelin/unknown-2008.json
.openzeppelin/unknown-2009.json
contracts/base/common/BlacklistableUpgradeable.sol
docs/deployed-contracts.md
test/base/ERC20Base.test.ts
test/base/ERC20Mintable.test.ts
test/base/common/BlacklistableUpgradeable.test.ts
test/periphery/YieldStreamer.test.ts

A flag indicating whether blacklist checks are enabled/disabled has been added to the contract. If this flag is disabled, then even if the account is blocked, all transactions on this account will be completed successfully.
Introduced functions:
``` Solidity
/**
* @notice Checks if the blacklist is enabled
* @return True if the blacklist is enabled, False otherwise
*/
function isBlacklistEnabled() public view returns (bool);
/**
* @notice Enables or disables the blacklist
* Requirements:
* - Can only be called by the owner
* Emits a {BlacklistEnabled} event
* @param status The new enabled/disabled status of the blacklist
*/
function enableBlacklist(bool status) external;
```
The BRLCToken, USJimToken and YieldStreamer contracts have been updated on the Mainnet and Testnet networks.
The …

Blacklistable contract improvements - enabling/disabling blacklist checks. 

---

.openzeppelin/unknown-2008.json
.openzeppelin/unknown-2009.json
contracts/periphery/YieldStreamer.sol
docs/deployed-contracts.md
test/periphery/YieldStreamer.test.ts

1. The `updateLookBackPeriod()` function has been added to the `YieldStreamer` smart contract:
```solidity
/**
* @notice Updates the look-back period at the specified index
* @param effectiveDay The index of the day the look-back period come into use
* @param length The length of the new look-back period in days
* @param index The index of the look-back period in the array
*/
function updateLookBackPeriod(uint256 effectiveDay, uint256 length,  uint256 index) external;
```
3. With the new function, updating the existing look-back period configuration will be possible.
The `updateLookBackPeriod()` function was fully covered by tests.
*Note:* The harness contracts don't need to be changed.

Update look-back period on YieldStreamer contract 

---

.openzeppelin/unknown-2008.json
.openzeppelin/unknown-2009.json
contracts/periphery/BalanceTracker.sol
docs/deployed-contracts.md
hardhat.config.ts
test/periphery/BalanceTracker.test.ts

**Main Changes**
This pull request adds temporary solution for testing that will be removed in the future. It adds a service testing account to `BalanceTracker` in the `getDailyBalances()` function with conditions:
- if the day index is less or equal 19703 (12 Dec 2023 BRT), the function provides 10 000 BRLC as the balance of the account;
- if the day index is higher than 19703, the function provides the actual balance of the account.
These changes lead to increased yield for the service account in the YieldStreamer contract.
**Test coverage**
File                                  |  % Stmts | % Branch |  % Funcs |  % Lines |
--------------------------------------|----------|----------|----------|----------|
contracts/                           |    94.37 |    66.67 |    87.88 |    94.37 …

Adding service account

---

contracts/periphery/YieldStreamer.sol
test/periphery/YieldStreamer.test.ts

**Main Changes**
This pull request adds `updateYieldRate` function to the YieldStreamer contract to provide the ability to edit yield rates.
- Can only be called by the contract owner
- Yield rate must be configured
- The index must be in range of yield rates array
- The new day must be equal or greater than previous and equal or less than next days
**Test coverage**
File                                  |  % Stmts | % Branch |  % Funcs |
--------------------------------------|----------|----------|----------|
contracts/                           |    94.37 |    66.67 |    87.88 |    94.37 |
&nbsp;&nbsp;&nbsp;&nbsp;BRLCToken.sol                       |      100 |    66.67 |      100 |      100 |
&nbsp;&nbsp;&nbsp;&nbsp;BRLCTokenBridgeable.sol             |    86.67 |    66.67 |    71.43 | …

Adding update yield rate function

---

contracts/BRLCToken.sol
contracts/BRLCTokenBridgeable.sol
contracts/USJimToken.sol
contracts/base/ERC20Freezable.sol
contracts/base/ERC20Mintable.sol
contracts/base/ERC20Restrictable.sol
contracts/base/interfaces/IERC20Mintable.sol
contracts/mocks/ERC20HookMock.sol
contracts/mocks/base/ERC20FreezableMock.sol
contracts/mocks/base/ERC20MintableMock.sol
test/BRLCToken.complex.test.ts
test/USJimToken.complex.test.ts
test/base/ERC20Mintable.test.ts

The new functionality allows tokens preminting for the users and makes those tokens only available in the future. Preminted tokens are minted like regular tokens but cannot be used until the release time. The release time for tokens is configured for each preminted amount.
1. New constant variable `_EXTENDED_STORAGE_SLOT` was introduced. This variable contains the storage slot that holds the data that is related to print functionality in the form of an `ExtendedStorageSlot` struct.
```Solidity
struct ExtendedStorageSlot {
mapping(address => PremintState) premints;
uint16 maxPendingPremintsCount;
}
```
2. New structure was introduced. This structure holds the data about each premint. The structure has a reserved variable for future expansions.
```solidity
struct PremintRecord {
uint64 …
```

Extend ERC20Mintable contract with premit functionality

---

contracts/base/CWToken.sol
contracts/base/ERC20Restrictable.sol
contracts/base/interfaces/IERC20ComplexBalance.sol
test/base/CWToken.complex.test.ts

With the implementation of the new functionality, contract now have the ability to retrieve the complex state of the account balance using a single function, `balanceOfComplex`. This function returns a data structure containing the current total balance of the account, as well as the amounts of free-to-use tokens, preminted tokens, frozen tokens, and restricted tokens.
Introduction of the `ComplexBalance` struct to store data pertaining to complex balance:
```solidity
struct ComplexBalance {
/// The total amount of tokens that is equal the value returned by the usual `ERC20.balanceOf()` function
uint256 total;
/// The amount of tokens that are available without any limitations described in the subsequent fields
uint256 free;
/// The total amount of pre-minted tokens of the account that …
```

Introduce balanceOfComplex function that allows to check preminted, frozen and restricted tokens in one call

---

contracts/base/ERC20Mintable.sol
contracts/base/interfaces/IERC20Mintable.sol
test/base/CWToken.complex.test.ts
test/base/ERC20Mintable.test.ts

With the implementation of the new functionality, the contract now has the ability to update or cancel pending (not expired) premints. Premint operation restrictions were added to limit some actions during the `premint()` function call.
New `premint()` function declaration:
```solidity
/// @notice An enum describing restrictions for premint operation
enum PremintRestriction {
None,   // No restriction
Create, // Creating a new premint is disallowed
Update // Updating an existing premint is disallowed
}
/**
* @notice Premints tokens
*
* Emits a {Premint} event
*
* @param account The address of a tokens recipient
* @param amount The amount of tokens to premint
* @param release The timestamp when the tokens will be released
* @param restriction The restriction for the premint operation
*/ …
```

Update premint logic

---

.openzeppelin/unknown-2008.json
contracts/base/CWToken.sol
contracts/base/ERC20Freezable.sol
test/base/ERC20Freezable.test.ts

In the current implementation of the `transferFrozen` function, it reverts with the error `TransferExceededFrozenAmount` in a situation where the frozen account balance exceeds the free balance. This PR solved this issue.
New functionality was fully covered with tests

Fix `transferFrozen` function when the frozen balance exceeds the free balance

---

.openzeppelin/unknown-2008.json
.openzeppelin/unknown-2009.json
contracts/base/ERC20Mintable.sol
contracts/base/interfaces/IERC20Mintable.sol
test/base/CWToken.complex.test.ts
test/base/ERC20Mintable.test.ts

1. The `premint()` function has been removed and replaced by two new functions:
* `premintIncrease()` -- for increasing the amount of an existing premint or creating a new one with the provided account address and release time;
* `premintDecrease()` -- for decreasing the amount of an existing premint.
2. The enumeration with premint restrictions has been removed as redundant for the new functions.
<details>
<summary>Functions declaration code</summary>
```solidity
/**
* @notice Increases the amount of an existing premint or creates a new one if it does not exist
*
* Emits a {Premint} event
*
* @param account The address of a tokens recipient
* @param amount The amount of tokens to increase
* @param release The timestamp when the tokens will be released
*/
function premintIncrease(
address …
```

Revision of the premint logic

---

contracts/base/ERC20Mintable.sol
contracts/base/interfaces/IERC20Mintable.sol
test/base/ERC20Mintable.test.ts

1. The ability to reschedule premints from one release timestamp to another has been implemented. The release that is rescheduled got named `original`. The new release that is configured instead of the `original` one got named `target`.
2. The configured reschedulings are applied to all premints: both existing and future. The logic is implemented by the mapping: `original release` => `target release`.
4. The new `reschedulePremints()` function has been added to configure the reschedulings.
5. The rescheduling logic are taken into account during defining the real release timestamp of premints.
6. The existing `getPremints()` function now returns premints for an account with the `release` field that is changed according to existing reshedulings if any is applied.
7. To remove one of the …

Premints rescheduling

---

contracts/base/ERC20Base.sol
contracts/base/ERC20Restrictable.sol
contracts/base/interfaces/IERC20Restrictable.sol
test/base/CWToken.complex.test.ts
test/base/ERC20Restrictable.test.ts

1. A new `restrictionIncrease()` function has been created to increase an existing restricted balance by a certain amount.
2. A new `restrictionDecrease()` function has been created to decrease an existing restricted balance by a certain amount.
3. An existing `updateRestriction()` function has been removed and replaced by the new function mentioned above.
```Solidity
/**
* @notice Increases the restriction balance for an account
*
* @param account The account to increase restriction for
* @param purpose The restriction purpose
* @param amount The amount to increase the restriction balance by
*/
function restrictionIncrease(address account, bytes32 purpose, uint256 amount) external;
/**
* @notice Decreases the restriction balance for an account
*
* @param account The account to decrease …
```

Add the ability to increase and decrease restricted balance

---

contracts/base/ERC20Restrictable.sol
contracts/base/interfaces/IERC20Restrictable.sol
test/base/ERC20Restrictable.test.ts

1. The `AssignPurposes` event has been renamed to `PurposesAssigned`.
2. The `UpdateRestriction` event has been renamed to `RestrictionUpdated`.
```Solidity
/**
* @notice Emitted when the restriction purposes are assigned to an account
*
* @param account The account the restriction purposes are assigned to
* @param newPurposes The array of the new restriction purposes
* @param oldPurposes The array of the old restriction purposes
*/
event PurposesAssigned(address indexed account, bytes32[] newPurposes, bytes32[] oldPurposes);
/**
* @notice Emitted when the restriction is updated for an account
*
* @param account The account the restriction is updated for
* @param purpose The restriction purpose
* @param newBalance The new restricted balance
* @param oldBalance The old restricted balance …
```

Rename IERC20Restrictable interface events

---

.openzeppelin/unknown-2008.json
.openzeppelin/unknown-2009.json
contracts/BRLCTokenBridgeable.sol
contracts/base/CWToken.sol
contracts/base/ERC20Freezable.sol
contracts/base/ERC20Mintable.sol
contracts/base/ERC20Restrictable.sol
contracts/mocks/base/ERC20FreezableMock.sol
contracts/mocks/base/ERC20MintableMock.sol
contracts/mocks/base/ERC20RestrictableMock.sol
test/base/CWToken.complex.test.ts
test/base/ERC20Freezable.test.ts
test/base/ERC20Mintable.test.ts
test/base/ERC20Restrictable.test.ts

1. The possibility to transfer frozen balance even if the related tokens are restricted has been added. E.g.:
* The `X` account has 100 tokens in total.
* 100 tokens are restricted to transfer only to account `A`.
* 10 tokens are frozen and expected to be transferred to account `B`.
* Despite of the restricted balance, the `transferFrozen()` function can transfer all 10 frozen tokens from `X` to `B`. Previously it did not work. The `transferFrozen()` function could only transfer tokens from `X` to the purposed account `A`.
2. All error checks related to complex balances have been moved from the internal `_afterTokenTransfer()` function of specific base contracts to the same-name internal function of the `CWToken` base contract. It allows to concentrate the check logic of the complex …

Improve the logic of the complex balance

---

.openzeppelin/unknown-2008.json
.openzeppelin/unknown-2009.json
contracts/base/ERC20Freezable.sol
contracts/base/interfaces/IERC20Freezable.sol
scripts/deployProxy.ts
scripts/prepareUpgrade.ts
test/base/ERC20Freezable.test.ts

1. A new function named `freezeIncrease()` has been created to increase an existing frozen balance by a certain amount.
2. A new function named `freezeDecrease()` has been created to decrease an existing frozen balance by a certain amount.
3. The existing `freeze()` function has been updated to prohibit the ability to use a zero address as account.
4. The existing `freeze()` function has been marked as `deprecated`. We are going to remove it in the future.
```Solidity
/**
* @notice Increases the frozen balance for an account
*
* Emits a {Freeze} event
*
* @param account The account to increase frozen balance for
* @param amount The amount to increase the frozen balance by
*/
function freezeIncrease(address account, uint256 amount) external;
/**
* @notice Decreases the frozen balance for …
```

Adding the possibility to increase and decrease frozen balance

---

.openzeppelin/unknown-2008.json
.openzeppelin/unknown-2009.json
contracts/base/ERC20Freezable.sol
contracts/base/interfaces/IERC20Freezable.sol
scripts/validateUpgrade.ts
test/base/CWToken.complex.test.ts
test/base/ERC20Freezable.test.ts

1. The new `freezer` role has been added to the contract. That role must be assigned to accounts that are executed the frozen balance related functions, like: `freezeIncrease()`, `freezeDecrease()`, `transferFrozen()`.
2. A new function named `configureFreezerBatch()` has been created to configure the freezer role for a batch of accounts.
3. A new modifier named `onlyFreezer` has been added to substitute `onlyBlockclister` modifier and checks if caller is freezer for the related functions.
```Solidity
/**
* @notice Configures a batch of freezers
*
* Emits a {FreezerAssigned} event for each assigned freezer
*
* Emits a {FreezerRemoved} event for each removed freezer
*
* @param freezers The array of freezer addresses to configure
* @param status The new status of the freezers: `true` is to …
```

feat: adding freezer role

---

.openzeppelin/unknown-2008.json
.openzeppelin/unknown-2009.json
contracts/base/ERC20Freezable.sol
contracts/base/interfaces/IERC20Freezable.sol
contracts/mocks/base/ERC20FreezableMock.sol
test/base/CWToken.complex.test.ts
test/base/ERC20Freezable.test.ts

1. The approval logic for freezing has been removed. Now the balance of any account in the blockchain can be frozen without preliminary approval of that account.
2. A check has been added to the existing freezing functions (`freezer()`, `freezeIncrease()`, `freezeDecrease()`) to ensure that the provided address does not belong to a smart-contract. Freezing the balance of existing smart-contracts is prohibited. If this requirement is violated, the freeze functions are reverted with the new `ContractBalanceFreezingAttempt` error.
3. In addition to the previous point, resetting frozen balances to zero for contracts is allowed. This is done to fix the extremely rare cases where the balance of some address was frozen before the contract was deployed to that address.
4. The `approveFreezing()` …

Remove freezing approval

---

.openzeppelin/unknown-2008.json
.openzeppelin/unknown-2009.json
README.md
package-lock.json
package.json

1. Upgraded `BRLCToken` and `USJimToken` contracts in Testnet.
2. Prepared `BRLCToken` and `USJimToken` contracts upgrade in Mainnet.
3. Updated `.openzeppelin` network files accordingly.

build: contract upgrade

---

contracts/legacy/LegacyRestrictablePlaceholder.sol

The `LegacyRestrictablePlaceholder` contract was missing a storage gap, which has been re-added.

fix: `LegacyRestrictablePlaceholder` storage

---

contracts/base/ERC20Base.sol
contracts/base/Versionable.sol
test/base/CWToken.test.ts
test/base/ERC20Base.test.ts

1. The new `setRoleAdmin()` function has been added to arbitrarily assign role admins in the contract: 
<details>
<summary>The definition of new function </summary>
```solidity
/**
* @notice Sets the admin role for a given role
*
* @dev This function is used to set the admin role for a given role
* @param role The role to set the admin role for
* @param adminRole The admin role to set
*/
function setRoleAdmin(bytes32 role, bytes32 adminRole) external onlyOwner {....}
```
</details>
2. The new function is necessary for future steps of the transition to [role-based access control](https://docs.openzeppelin.com/contracts/5.x/access-control#role-based-access-control).
The smart contracts version has been updated to `v.1.4.1`.
The new function has been fully covered by unit tests.
<details> …

fix: add the function to configure role admins

---

contracts/BRLCToken.sol
contracts/USJimToken.sol
contracts/base/CWToken.sol
contracts/base/ERC20Base.sol
contracts/base/ERC20Freezable.sol
contracts/base/ERC20Hookable.sol
contracts/base/ERC20Mintable.sol
contracts/base/ERC20Trustable.sol
contracts/base/Versionable.sol
contracts/base/core/AccessControlExtUpgradeable.sol
contracts/base/core/PausableExtUpgradeable.sol
contracts/base/core/RescuableUpgradeable.sol
contracts/mocks/base/CWTokenMock.sol
contracts/mocks/base/ERC20BaseMock.sol
contracts/mocks/base/ERC20FreezableMock.sol
contracts/mocks/base/ERC20HookableMock.sol
contracts/mocks/base/ERC20MintableMock.sol
contracts/mocks/base/ERC20TrustableMock.sol
contracts/mocks/base/core/AccessControlExtUpgradeableMock.sol
contracts/mocks/base/core/PausableExtUpgradeableMock.sol
contracts/mocks/base/core/RescuableUpgradeableMock.sol
test/BRLCToken.test.ts
test/USJimToken.test.ts
test/base/CWToken.complex.test.ts
test/base/CWToken.test.ts
test/base/ERC20Mintable.test.ts

1. A typo has been fixed in the role name: `PREMINT_MANGER_ROLE` => `PREMINT_MANAGER_ROLE` (letter `A` in the middle of the `manager` word). The new role hash is: `0x402cbf9f98ff4d50944d71007c65c57c5d98c1016412845fade656a0e6948d6d`.
2. Other typos have been fixed in comments.
The smart contracts version has been updated to `v.1.5.1`.
IMPORTANT! Do NOT upgrade the existing contracts before executing the steps below for each of them:
1. Using the block explorer database or a similar service to get the list of all addresses that have previously been granted the wrong old `PREMINT_MANGER_ROLE` role.
2. Grant the new correct `PREMINT_MANAGER_ROLE` role for each address from the list (step 1) using the `grantRole()` or `grantRoleBatch()` functions.
3. Now you can safely upgrade the smart …

fix: correct a role name

---

.env.example
hardhat.config.ts
package-lock.json

- Added Stratus network configuration to use that repository in Stratus e2e tests
- Removed `OPTIMIZER_ENABLED` and `SOLIDITY_VERSION ` configurations
Tests can now be run without providing a `.env` file (they use the Hardhat network by default).

ci: add stratus network configuration and refactor defaults
